name: 'Release Helper'
description: 'Helps manage release-related issues.'
inputs:
  token:
    description: 'The GitHub token'
    required: false
    default: ${{ github.token }}
  issue_number:
    required: false
    default: ${{ github.event }}

runs:
  using: 'node16'
  main: 'index.js'

  